config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources:cocktails do
    resources:doses, only: [:new,:create,:show]
  end
  delete 'doses/:id(.:format)', :to => 'doses#destroy', as: "delete_dose"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, presence: true, :allow_nil => false
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index #DONE
    @cocktails = Cocktail.all
  end

  def show #DONE
  end

  def new #DONE
    @cocktail = Cocktail.new
  end

  def create #DONE
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit #DONE
    @cocktail = Cocktail.find(params[:id])
  end

  def update #DONE
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy #DONE
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:show, :edit, :update]

  def index #DONE
    @doses = Dose.all
  end

  def show #DONE
  end

  def new #DONE
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create #DONE
    @dose = Dose.new(dose_params)

    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail_id = @cocktail.id
    @dose.ingredient_id = params[:dose][:ingredient_id]
    if @dose.save || @ingredient.nil? == false
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit #DONE
    @dose = Dose.find(params[:id])
  end

  def update #DONE
    @dose.update(dose_params)
    redirect_to doses_path
  end

  def destroy #DONE
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :amount, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="wrapper">
  <div class="large-card">
    <div class="header">
      <h1>Editing cocktail</h1>
    </div>

    <%= form_for(@cocktail) do |f| %>
    <div class="form">
      <div class="box">
        <div class="row" id="title-row">Title</div>
        <div class="row">
          <%= f.text_field :name %>
        </div>
      </div>
    </div>
    <%= f.submit %>
    <% end %>
    <%= link_to "Cancel", cocktails_path  %>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="title"> <h1> Mig's Recipes </h1> </div>
<div class="container">

  <hr>

  <div class="menu">
    <%= link_to "Popular Cocktails", new_cocktail_path, class: "menu_item"%>
    <%= link_to "Random Cocktail", new_cocktail_path, class: "menu_item"%>
    <%= link_to "Add A Cocktail", new_cocktail_path, class: "menu_item"%>
    <%= link_to "About Us", new_cocktail_path, class: "menu_item"%>
    <%= link_to "Contact", new_cocktail_path, class: "menu_item"%>
  </div>

  <hr>

  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="fixed-card">
        <div class="cocktail-image">
          <%= cl_image_tag cocktail.photo, class: "drink_image" %>
        </div>
        <div class="cocktail-text">
          <div class="cocktail-card-content">
            <div class="cocktail-card-title">
              <p><%= link_to cocktail.name, cocktail_path(cocktail) %></p>
            </div>
            <div> <p> <%= cocktail.doses.count%> <%= cocktail.doses.count == 1 ? "Ingredient" : "Ingredients" %></p></div>
          </div>
          <div class="card-actions">
            <%= link_to "More Info" , cocktail_path(cocktail) %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/cocktails/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="cocktail-form">
        <h1>Add a new cocktail</h1>
        <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="buttons">
          <%= f.button :submit %>
          <%= link_to "Cancel", cocktails_path, class: "btn btn-warning"%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="large-card">
  <h1><%= @cocktail.name %></h1>

  <div class="content">
    <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill, class: "drink_image" %>

    <div class="ingredients">
      <ul>
        <h4>Ingredients</h4>
        <% @cocktail.doses.each do |dose| %>
        <li>
          <%= dose.amount  %>
          <%= dose.ingredient.name  %>
          <%= dose.description  %>
          <br>
          <%= link_to "Delete Ingredient", delete_dose_path(dose), method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="buttons">
    <%= link_to "Add Ingredients", new_cocktail_dose_path(@cocktail), class: "btn" %>
    <%= link_to 'Delete', cocktail_path(@cocktail), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
    <%= link_to "Go back", cocktails_path, class: "btn" %>
  </div>
</div>

app/views/doses/edit.html.erb
<div class="wrapper">
  <div class="large-card">
    <div class="header">
      <h1>Editing Flat</h1>
    </div>

    <%= form_for(@flat) do |f| %>
    <div class="form">
      <div class="box">
        <div class="row" id="title-row">Title</div>
        <div class="row">
          <%= f.text_field :name %>
        </div>
      </div>
    </div>
    <%= f.submit %>
    <% end %>
    <%= link_to "Cancel", flats_path  %>
  </div>
</div>

app/views/doses/index.html.erb
<div class="navbar">
  <div class="menu">
   <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="" id="search">
   <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
   <%= link_to "Add A Flat", new_flat_path %>
 </div>
</div>

<div class="title">
  <h1>All our Flats</h1>
  <p>We found 3 flats out of our 3 on our website.</p>
</div>

<div class="container">

  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="flat-card">
        <div class="flat-card-content">
          <div class="flat-card-title">
            <h4><%= link_to flat.name, flat_path(flat) %></h4>
          </div>
          <p><%=flat.address %></p>
          <div class="flex">
            <div class="flex">
              <i class="material-icons mr-2">people </i><span>
                <p> <%= flat.number_of_guests %></p>
              </span>
            </div>
            <div class="flex ml-3">
              <i class="material-icons mr-2">euro_symbol</i>
              <p> <%= flat.price_per_night %></p>
            </div>
          </div>
        </div>
        <div class="flat-card-actions">
          <%= link_to "More Info" , flat_path(flat) %>
          <%= link_to "Edit", edit_flat_path(flat, :class => "ml-3 text-warning")  %>
          <%= link_to 'Delete', flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' }, :class => "ml-3 text-danger" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="cocktail-form">
        <h1>Add a new ingredient</h1>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description %>
        <%= f.input :amount %>
        <%= f.association :ingredient%>
        <div class="buttons">
          <%= f.button :submit %>
          <%= link_to "Cancel Dose", cocktail_path(@cocktail), class: "btn btn-warning"%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/miguel-aguilera-croasdaile" target="blank"><i class="fa fa-github"></i></a>
    <a href="https://www.instagram.com/mig.aguilera/" target="blank"><i class="fa fa-instagram"></i></a>
    <a href="https://www.facebook.com/profile.php?id=100006446462047" target="blank"><i class="fa fa-facebook"></i></a>
    <a href="https://www.linkedin.com/in/miguel-aguilera-croasdaile-666420152/" target="blank"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>